package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user.id";

	public static final String ID = "ID";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String name = "user.name";

	public static final String NAME = "NAME";

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	public java.lang.String getMail() {
		return get("mail");
	}

	public static final String mail = "user.mail";

	public static final String MAIL = "MAIL";

	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}

	public java.lang.String getNick() {
		return get("nick");
	}

	public static final String nick = "user.nick";

	public static final String NICK = "NICK";

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public static final String password = "user.password";

	public static final String PASSWORD = "PASSWORD";

	public void setPasssalt(java.lang.String passsalt) {
		set("passsalt", passsalt);
	}

	public java.lang.String getPasssalt() {
		return get("passsalt");
	}

	public static final String passsalt = "user.passsalt";

	public static final String PASSSALT = "PASSSALT";

	public void setLocked(java.lang.Boolean locked) {
		set("locked", locked);
	}

	public java.lang.Boolean getLocked() {
		return get("locked");
	}

	public static final String locked = "user.locked";

	public static final String LOCKED = "LOCKED";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "user.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "user.*";
	public static final String TABLE_NAME = "user";}
