package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVwTopicUserAttitudePw<M extends BaseVwTopicUserAttitudePw<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "vw_topic_user_attitude_pw.id";

	public static final String ID = "ID";

	public void setUtvaPw(java.lang.Long utvaPw) {
		set("utvaPw", utvaPw);
	}

	public java.lang.Long getUtvaPw() {
		return get("utvaPw");
	}

	public static final String utvapw = "vw_topic_user_attitude_pw.utvaPw";

	public static final String UTVAPW = "UTVAPW";

	public static final String ALL_FIELDS = "vw_topic_user_attitude_pw.*";
	public static final String TABLE_NAME = "vw_topic_user_attitude_pw";}
