package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTopicCommentStatus<M extends BaseSysTopicCommentStatus<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_topic_comment_status.id";

	public static final String ID = "ID";

	public void setAbbr(java.lang.String abbr) {
		set("abbr", abbr);
	}

	public java.lang.String getAbbr() {
		return get("abbr");
	}

	public static final String abbr = "sys_topic_comment_status.abbr";

	public static final String ABBR = "ABBR";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String name = "sys_topic_comment_status.name";

	public static final String NAME = "NAME";

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public static final String description = "sys_topic_comment_status.description";

	public static final String DESCRIPTION = "DESCRIPTION";

	public void setVisible(java.lang.Integer visible) {
		set("visible", visible);
	}

	public java.lang.Integer getVisible() {
		return get("visible");
	}

	public static final String visible = "sys_topic_comment_status.visible";

	public static final String VISIBLE = "VISIBLE";

	public void setEditable(java.lang.Integer editable) {
		set("editable", editable);
	}

	public java.lang.Integer getEditable() {
		return get("editable");
	}

	public static final String editable = "sys_topic_comment_status.editable";

	public static final String EDITABLE = "EDITABLE";

	public void setLock(java.lang.Integer lock) {
		set("lock", lock);
	}

	public java.lang.Integer getLock() {
		return get("lock");
	}

	public static final String lock = "sys_topic_comment_status.lock";

	public static final String LOCK = "LOCK";

	public void setRelease(java.lang.Integer release) {
		set("release", release);
	}

	public java.lang.Integer getRelease() {
		return get("release");
	}

	public static final String release = "sys_topic_comment_status.release";

	public static final String RELEASE = "RELEASE";

	public void setDelete(java.lang.Integer delete) {
		set("delete", delete);
	}

	public java.lang.Integer getDelete() {
		return get("delete");
	}

	public static final String delete = "sys_topic_comment_status.delete";

	public static final String DELETE = "DELETE";

	public void setMove(java.lang.Integer move) {
		set("move", move);
	}

	public java.lang.Integer getMove() {
		return get("move");
	}

	public static final String move = "sys_topic_comment_status.move";

	public static final String MOVE = "MOVE";

	public void setComment(java.lang.Integer comment) {
		set("comment", comment);
	}

	public java.lang.Integer getComment() {
		return get("comment");
	}

	public static final String comment = "sys_topic_comment_status.comment";

	public static final String COMMENT = "COMMENT";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_topic_comment_status.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_topic_comment_status.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_topic_comment_status.*";
	public static final String TABLE_NAME = "sys_topic_comment_status";}
