package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMessage<M extends BaseUserMessage<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_message.id";

	public static final String ID = "ID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_message.userId";

	public static final String USERID = "USERID";

	public void setDestUser(java.lang.Integer destUser) {
		set("destUser", destUser);
	}

	public java.lang.Integer getDestUser() {
		return get("destUser");
	}

	public static final String destuser = "user_message.destUser";

	public static final String DESTUSER = "DESTUSER";

	public void setRead(java.lang.Integer read) {
		set("read", read);
	}

	public java.lang.Integer getRead() {
		return get("read");
	}

	public static final String read = "user_message.read";

	public static final String READ = "READ";

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public static final String title = "user_message.title";

	public static final String TITLE = "TITLE";

	public void setBody(java.lang.String body) {
		set("body", body);
	}

	public java.lang.String getBody() {
		return get("body");
	}

	public static final String body = "user_message.body";

	public static final String BODY = "BODY";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user_message.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "user_message.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "user_message.*";
	public static final String TABLE_NAME = "user_message";}
