package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysAreaStatus<M extends BaseSysAreaStatus<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_area_status.id";

	public static final String ID = "ID";

	public void setAbbr(java.lang.String abbr) {
		set("abbr", abbr);
	}

	public java.lang.String getAbbr() {
		return get("abbr");
	}

	public static final String abbr = "sys_area_status.abbr";

	public static final String ABBR = "ABBR";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String name = "sys_area_status.name";

	public static final String NAME = "NAME";

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public static final String description = "sys_area_status.description";

	public static final String DESCRIPTION = "DESCRIPTION";

	public void setVisible(java.lang.Integer visible) {
		set("visible", visible);
	}

	public java.lang.Integer getVisible() {
		return get("visible");
	}

	public static final String visible = "sys_area_status.visible";

	public static final String VISIBLE = "VISIBLE";

	public void setClose(java.lang.Integer close) {
		set("close", close);
	}

	public java.lang.Integer getClose() {
		return get("close");
	}

	public static final String close = "sys_area_status.close";

	public static final String CLOSE = "CLOSE";

	public void setMove(java.lang.Integer move) {
		set("move", move);
	}

	public java.lang.Integer getMove() {
		return get("move");
	}

	public static final String move = "sys_area_status.move";

	public static final String MOVE = "MOVE";

	public void setPubTopic(java.lang.Integer pubTopic) {
		set("pubTopic", pubTopic);
	}

	public java.lang.Integer getPubTopic() {
		return get("pubTopic");
	}

	public static final String pubtopic = "sys_area_status.pubTopic";

	public static final String PUBTOPIC = "PUBTOPIC";

	public void setPubComment(java.lang.Integer pubComment) {
		set("pubComment", pubComment);
	}

	public java.lang.Integer getPubComment() {
		return get("pubComment");
	}

	public static final String pubcomment = "sys_area_status.pubComment";

	public static final String PUBCOMMENT = "PUBCOMMENT";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_area_status.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdaetTime(java.util.Date updaetTime) {
		set("updaetTime", updaetTime);
	}

	public java.util.Date getUpdaetTime() {
		return get("updaetTime");
	}

	public static final String updaettime = "sys_area_status.updaetTime";

	public static final String UPDAETTIME = "UPDAETTIME";

	public static final String ALL_FIELDS = "sys_area_status.*";
	public static final String TABLE_NAME = "sys_area_status";}
