package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_address.id";

	public static final String ID = "ID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_address.userId";

	public static final String USERID = "USERID";

	public void setProvince(java.lang.Integer province) {
		set("province", province);
	}

	public java.lang.Integer getProvince() {
		return get("province");
	}

	public static final String province = "user_address.province";

	public static final String PROVINCE = "PROVINCE";

	public void setCity(java.lang.Integer city) {
		set("city", city);
	}

	public java.lang.Integer getCity() {
		return get("city");
	}

	public static final String city = "user_address.city";

	public static final String CITY = "CITY";

	public void setRegion(java.lang.Integer region) {
		set("region", region);
	}

	public java.lang.Integer getRegion() {
		return get("region");
	}

	public static final String region = "user_address.region";

	public static final String REGION = "REGION";

	public void setStreet(java.lang.Integer street) {
		set("street", street);
	}

	public java.lang.Integer getStreet() {
		return get("street");
	}

	public static final String street = "user_address.street";

	public static final String STREET = "STREET";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user_address.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "user_address.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "user_address.*";
	public static final String TABLE_NAME = "user_address";}
