package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserExtend<M extends BaseUserExtend<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_extend.id";

	public static final String ID = "ID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_extend.userId";

	public static final String USERID = "USERID";

	public void setWebSite(java.lang.String webSite) {
		set("webSite", webSite);
	}

	public java.lang.String getWebSite() {
		return get("webSite");
	}

	public static final String website = "user_extend.webSite";

	public static final String WEBSITE = "WEBSITE";

	public void setGithub(java.lang.String github) {
		set("github", github);
	}

	public java.lang.String getGithub() {
		return get("github");
	}

	public static final String github = "user_extend.github";

	public static final String GITHUB = "GITHUB";

	public void setTwitter(java.lang.String twitter) {
		set("twitter", twitter);
	}

	public java.lang.String getTwitter() {
		return get("twitter");
	}

	public static final String twitter = "user_extend.twitter";

	public static final String TWITTER = "TWITTER";

	public void setFacebook(java.lang.String facebook) {
		set("facebook", facebook);
	}

	public java.lang.String getFacebook() {
		return get("facebook");
	}

	public static final String facebook = "user_extend.facebook";

	public static final String FACEBOOK = "FACEBOOK";

	public void setGoogle(java.lang.String google) {
		set("google", google);
	}

	public java.lang.String getGoogle() {
		return get("google");
	}

	public static final String google = "user_extend.google";

	public static final String GOOGLE = "GOOGLE";

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public static final String qq = "user_extend.qq";

	public static final String QQ = "QQ";

	public static final String ALL_FIELDS = "user_extend.*";
	public static final String TABLE_NAME = "user_extend";}
