package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserBasicinfo<M extends BaseUserBasicinfo<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_basicinfo.id";

	public static final String ID = "ID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_basicinfo.userId";

	public static final String USERID = "USERID";

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phoneNumber");
	}

	public static final String phonenumber = "user_basicinfo.phoneNumber";

	public static final String PHONENUMBER = "PHONENUMBER";

	public void setSign(java.lang.String sign) {
		set("sign", sign);
	}

	public java.lang.String getSign() {
		return get("sign");
	}

	public static final String sign = "user_basicinfo.sign";

	public static final String SIGN = "SIGN";

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}

	public static final String avatar = "user_basicinfo.avatar";

	public static final String AVATAR = "AVATAR";

	public void setWebSite(java.lang.String webSite) {
		set("webSite", webSite);
	}

	public java.lang.String getWebSite() {
		return get("webSite");
	}

	public static final String website = "user_basicinfo.webSite";

	public static final String WEBSITE = "WEBSITE";

	public void setBirth(java.util.Date birth) {
		set("birth", birth);
	}

	public java.util.Date getBirth() {
		return get("birth");
	}

	public static final String birth = "user_basicinfo.birth";

	public static final String BIRTH = "BIRTH";

	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public static final String balance = "user_basicinfo.balance";

	public static final String BALANCE = "BALANCE";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user_basicinfo.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "user_basicinfo.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "user_basicinfo.*";
	public static final String TABLE_NAME = "user_basicinfo";}
