package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopicStatus<M extends BaseTopicStatus<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "topic_status.id";

	public static final String ID = "ID";

	public void setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topicId");
	}

	public static final String topicid = "topic_status.topicId";

	public static final String TOPICID = "TOPICID";

	public void setStatusId(java.lang.Integer statusId) {
		set("statusId", statusId);
	}

	public java.lang.Integer getStatusId() {
		return get("statusId");
	}

	public static final String statusid = "topic_status.statusId";

	public static final String STATUSID = "STATUSID";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "topic_status.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "topic_status.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "topic_status.*";
	public static final String TABLE_NAME = "topic_status";}
