package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTopic<M extends BaseSysTopic<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_topic.id";

	public static final String ID = "ID";

	public void setAreaId(java.lang.Integer areaId) {
		set("areaId", areaId);
	}

	public java.lang.Integer getAreaId() {
		return get("areaId");
	}

	public static final String areaid = "sys_topic.areaId";

	public static final String AREAID = "AREAID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "sys_topic.userId";

	public static final String USERID = "USERID";

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public static final String url = "sys_topic.url";

	public static final String URL = "URL";

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public static final String title = "sys_topic.title";

	public static final String TITLE = "TITLE";

	public void setBody(java.lang.String body) {
		set("body", body);
	}

	public java.lang.String getBody() {
		return get("body");
	}

	public static final String body = "sys_topic.body";

	public static final String BODY = "BODY";

	public void setTcStatusId(java.lang.Integer tcStatusId) {
		set("tcStatusId", tcStatusId);
	}

	public java.lang.Integer getTcStatusId() {
		return get("tcStatusId");
	}

	public static final String tcstatusid = "sys_topic.tcStatusId";

	public static final String TCSTATUSID = "TCSTATUSID";

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public static final String count = "sys_topic.count";

	public static final String COUNT = "COUNT";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_topic.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_topic.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_topic.*";
	public static final String TABLE_NAME = "sys_topic";}
