package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysComment<M extends BaseSysComment<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_comment.id";

	public static final String ID = "ID";

	public void setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topicId");
	}

	public static final String topicid = "sys_comment.topicId";

	public static final String TOPICID = "TOPICID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "sys_comment.userId";

	public static final String USERID = "USERID";

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}

	public java.lang.Integer getOrder() {
		return get("order");
	}

	public static final String order = "sys_comment.order";

	public static final String ORDER = "ORDER";

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public static final String title = "sys_comment.title";

	public static final String TITLE = "TITLE";

	public void setBody(java.lang.String body) {
		set("body", body);
	}

	public java.lang.String getBody() {
		return get("body");
	}

	public static final String body = "sys_comment.body";

	public static final String BODY = "BODY";

	public void setTcStatusId(java.lang.Integer tcStatusId) {
		set("tcStatusId", tcStatusId);
	}

	public java.lang.Integer getTcStatusId() {
		return get("tcStatusId");
	}

	public static final String tcstatusid = "sys_comment.tcStatusId";

	public static final String TCSTATUSID = "TCSTATUSID";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_comment.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_comment.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_comment.*";
	public static final String TABLE_NAME = "sys_comment";}
