package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUrlRole<M extends BaseSysUrlRole<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_url_role.id";

	public static final String ID = "ID";

	public void setActionKey(java.lang.String actionKey) {
		set("actionKey", actionKey);
	}

	public java.lang.String getActionKey() {
		return get("actionKey");
	}

	public static final String actionkey = "sys_url_role.actionKey";

	public static final String ACTIONKEY = "ACTIONKEY";

	public void setRole(java.lang.String role) {
		set("role", role);
	}

	public java.lang.String getRole() {
		return get("role");
	}

	public static final String role = "sys_url_role.role";

	public static final String ROLE = "ROLE";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_url_role.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_url_role.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_url_role.*";
	public static final String TABLE_NAME = "sys_url_role";}
