package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTopicViewAttitude<M extends BaseUserTopicViewAttitude<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_topic_view_attitude.id";

	public static final String ID = "ID";

	public void setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topicId");
	}

	public static final String topicid = "user_topic_view_attitude.topicId";

	public static final String TOPICID = "TOPICID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_topic_view_attitude.userId";

	public static final String USERID = "USERID";

	public void setAttitude(java.lang.Integer attitude) {
		set("attitude", attitude);
	}

	public java.lang.Integer getAttitude() {
		return get("attitude");
	}

	public static final String attitude = "user_topic_view_attitude.attitude";

	public static final String ATTITUDE = "ATTITUDE";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user_topic_view_attitude.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdaeTime(java.util.Date updaeTime) {
		set("updaeTime", updaeTime);
	}

	public java.util.Date getUpdaeTime() {
		return get("updaeTime");
	}

	public static final String updaetime = "user_topic_view_attitude.updaeTime";

	public static final String UPDAETIME = "UPDAETIME";

	public static final String ALL_FIELDS = "user_topic_view_attitude.*";
	public static final String TABLE_NAME = "user_topic_view_attitude";}
