package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysHistoryTop<M extends BaseSysHistoryTop<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_history_top.id";

	public static final String ID = "ID";

	public void setTopicIds(java.lang.String topicIds) {
		set("topicIds", topicIds);
	}

	public java.lang.String getTopicIds() {
		return get("topicIds");
	}

	public static final String topicids = "sys_history_top.topicIds";

	public static final String TOPICIDS = "TOPICIDS";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_history_top.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_history_top.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_history_top.*";
	public static final String TABLE_NAME = "sys_history_top";}
