package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTopicAttach<M extends BaseSysTopicAttach<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_topic_attach.id";

	public static final String ID = "ID";

	public void setTopicId(java.lang.Integer topicId) {
		set("topicId", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topicId");
	}

	public static final String topicid = "sys_topic_attach.topicId";

	public static final String TOPICID = "TOPICID";

	public void setAttachPath(java.lang.Integer attachPath) {
		set("attachPath", attachPath);
	}

	public java.lang.Integer getAttachPath() {
		return get("attachPath");
	}

	public static final String attachpath = "sys_topic_attach.attachPath";

	public static final String ATTACHPATH = "ATTACHPATH";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "sys_topic_attach.userId";

	public static final String USERID = "USERID";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_topic_attach.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_topic_attach.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_topic_attach.*";
	public static final String TABLE_NAME = "sys_topic_attach";}
