package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVwTopic<M extends BaseVwTopic<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "vw_topic.id";

	public static final String ID = "ID";

	public void setAreaId(java.lang.Integer areaId) {
		set("areaId", areaId);
	}

	public java.lang.Integer getAreaId() {
		return get("areaId");
	}

	public static final String areaid = "vw_topic.areaId";

	public static final String AREAID = "AREAID";

	public void setAuthorId(java.lang.Integer authorId) {
		set("authorId", authorId);
	}

	public java.lang.Integer getAuthorId() {
		return get("authorId");
	}

	public static final String authorid = "vw_topic.authorId";

	public static final String AUTHORID = "AUTHORID";

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public static final String title = "vw_topic.title";

	public static final String TITLE = "TITLE";

	public void setPubTime(java.util.Date pubTime) {
		set("pubTime", pubTime);
	}

	public java.util.Date getPubTime() {
		return get("pubTime");
	}

	public static final String pubtime = "vw_topic.pubTime";

	public static final String PUBTIME = "PUBTIME";

	public void setAreaAbbr(java.lang.String areaAbbr) {
		set("areaAbbr", areaAbbr);
	}

	public java.lang.String getAreaAbbr() {
		return get("areaAbbr");
	}

	public static final String areaabbr = "vw_topic.areaAbbr";

	public static final String AREAABBR = "AREAABBR";

	public void setAreaName(java.lang.String areaName) {
		set("areaName", areaName);
	}

	public java.lang.String getAreaName() {
		return get("areaName");
	}

	public static final String areaname = "vw_topic.areaName";

	public static final String AREANAME = "AREANAME";

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public static final String author = "vw_topic.author";

	public static final String AUTHOR = "AUTHOR";

	public void setAuthorAvatar(java.lang.String authorAvatar) {
		set("authorAvatar", authorAvatar);
	}

	public java.lang.String getAuthorAvatar() {
		return get("authorAvatar");
	}

	public static final String authoravatar = "vw_topic.authorAvatar";

	public static final String AUTHORAVATAR = "AUTHORAVATAR";

	public void setCount(java.lang.Long count) {
		set("count", count);
	}

	public java.lang.Long getCount() {
		return get("count");
	}

	public static final String count = "vw_topic.count";

	public static final String COUNT = "COUNT";

	public void setLastCommentId(java.lang.Integer lastCommentId) {
		set("lastCommentId", lastCommentId);
	}

	public java.lang.Integer getLastCommentId() {
		return get("lastCommentId");
	}

	public static final String lastcommentid = "vw_topic.lastCommentId";

	public static final String LASTCOMMENTID = "LASTCOMMENTID";

	public void setLastUser(java.lang.Integer lastUser) {
		set("lastUser", lastUser);
	}

	public java.lang.Integer getLastUser() {
		return get("lastUser");
	}

	public static final String lastuser = "vw_topic.lastUser";

	public static final String LASTUSER = "LASTUSER";

	public void setLastUserNick(java.lang.String lastUserNick) {
		set("lastUserNick", lastUserNick);
	}

	public java.lang.String getLastUserNick() {
		return get("lastUserNick");
	}

	public static final String lastusernick = "vw_topic.lastUserNick";

	public static final String LASTUSERNICK = "LASTUSERNICK";

	public void setLastCommentOrder(java.lang.Integer lastCommentOrder) {
		set("lastCommentOrder", lastCommentOrder);
	}

	public java.lang.Integer getLastCommentOrder() {
		return get("lastCommentOrder");
	}

	public static final String lastcommentorder = "vw_topic.lastCommentOrder";

	public static final String LASTCOMMENTORDER = "LASTCOMMENTORDER";

	public void setLastCommentTime(java.util.Date lastCommentTime) {
		set("lastCommentTime", lastCommentTime);
	}

	public java.util.Date getLastCommentTime() {
		return get("lastCommentTime");
	}

	public static final String lastcommenttime = "vw_topic.lastCommentTime";

	public static final String LASTCOMMENTTIME = "LASTCOMMENTTIME";

	public static final String ALL_FIELDS = "vw_topic.*";
	public static final String TABLE_NAME = "vw_topic";}
