package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVwUserRolePermission<M extends BaseVwUserRolePermission<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "vw_user_role_permission.id";

	public static final String ID = "ID";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String name = "vw_user_role_permission.name";

	public static final String NAME = "NAME";

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	public java.lang.String getMail() {
		return get("mail");
	}

	public static final String mail = "vw_user_role_permission.mail";

	public static final String MAIL = "MAIL";

	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}

	public java.lang.String getNick() {
		return get("nick");
	}

	public static final String nick = "vw_user_role_permission.nick";

	public static final String NICK = "NICK";

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public static final String password = "vw_user_role_permission.password";

	public static final String PASSWORD = "PASSWORD";

	public void setPasssalt(java.lang.String passsalt) {
		set("passsalt", passsalt);
	}

	public java.lang.String getPasssalt() {
		return get("passsalt");
	}

	public static final String passsalt = "vw_user_role_permission.passsalt";

	public static final String PASSSALT = "PASSSALT";

	public void setLocked(java.lang.Boolean locked) {
		set("locked", locked);
	}

	public java.lang.Boolean getLocked() {
		return get("locked");
	}

	public static final String locked = "vw_user_role_permission.locked";

	public static final String LOCKED = "LOCKED";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "vw_user_role_permission.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "vw_user_role_permission.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public void setRoleAbbr(java.lang.String roleAbbr) {
		set("roleAbbr", roleAbbr);
	}

	public java.lang.String getRoleAbbr() {
		return get("roleAbbr");
	}

	public static final String roleabbr = "vw_user_role_permission.roleAbbr";

	public static final String ROLEABBR = "ROLEABBR";

	public void setPermissionAbbr(java.lang.String permissionAbbr) {
		set("permissionAbbr", permissionAbbr);
	}

	public java.lang.String getPermissionAbbr() {
		return get("permissionAbbr");
	}

	public static final String permissionabbr = "vw_user_role_permission.permissionAbbr";

	public static final String PERMISSIONABBR = "PERMISSIONABBR";

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}

	public java.lang.String getRoleName() {
		return get("roleName");
	}

	public static final String rolename = "vw_user_role_permission.roleName";

	public static final String ROLENAME = "ROLENAME";

	public void setRoleDescription(java.lang.String roleDescription) {
		set("roleDescription", roleDescription);
	}

	public java.lang.String getRoleDescription() {
		return get("roleDescription");
	}

	public static final String roledescription = "vw_user_role_permission.roleDescription";

	public static final String ROLEDESCRIPTION = "ROLEDESCRIPTION";

	public void setRoleAvailable(java.lang.Integer roleAvailable) {
		set("roleAvailable", roleAvailable);
	}

	public java.lang.Integer getRoleAvailable() {
		return get("roleAvailable");
	}

	public static final String roleavailable = "vw_user_role_permission.roleAvailable";

	public static final String ROLEAVAILABLE = "ROLEAVAILABLE";

	public void setPermissionName(java.lang.String permissionName) {
		set("permissionName", permissionName);
	}

	public java.lang.String getPermissionName() {
		return get("permissionName");
	}

	public static final String permissionname = "vw_user_role_permission.permissionName";

	public static final String PERMISSIONNAME = "PERMISSIONNAME";

	public void setPermissionDescription(java.lang.String permissionDescription) {
		set("permissionDescription", permissionDescription);
	}

	public java.lang.String getPermissionDescription() {
		return get("permissionDescription");
	}

	public static final String permissiondescription = "vw_user_role_permission.permissionDescription";

	public static final String PERMISSIONDESCRIPTION = "PERMISSIONDESCRIPTION";

	public void setPermissionAvailable(java.lang.Integer permissionAvailable) {
		set("permissionAvailable", permissionAvailable);
	}

	public java.lang.Integer getPermissionAvailable() {
		return get("permissionAvailable");
	}

	public static final String permissionavailable = "vw_user_role_permission.permissionAvailable";

	public static final String PERMISSIONAVAILABLE = "PERMISSIONAVAILABLE";

	public void setRoleEndTime(java.util.Date roleEndTime) {
		set("roleEndTime", roleEndTime);
	}

	public java.util.Date getRoleEndTime() {
		return get("roleEndTime");
	}

	public static final String roleendtime = "vw_user_role_permission.roleEndTime";

	public static final String ROLEENDTIME = "ROLEENDTIME";

	public static final String ALL_FIELDS = "vw_user_role_permission.*";
	public static final String TABLE_NAME = "vw_user_role_permission";}
