package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysCommentAttach<M extends BaseSysCommentAttach<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "sys_comment_attach.id";

	public static final String ID = "ID";

	public void setCommentId(java.lang.Integer commentId) {
		set("commentId", commentId);
	}

	public java.lang.Integer getCommentId() {
		return get("commentId");
	}

	public static final String commentid = "sys_comment_attach.commentId";

	public static final String COMMENTID = "COMMENTID";

	public void setAttachPath(java.lang.String attachPath) {
		set("attachPath", attachPath);
	}

	public java.lang.String getAttachPath() {
		return get("attachPath");
	}

	public static final String attachpath = "sys_comment_attach.attachPath";

	public static final String ATTACHPATH = "ATTACHPATH";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "sys_comment_attach.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "sys_comment_attach.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "sys_comment_attach.*";
	public static final String TABLE_NAME = "sys_comment_attach";}
