package com.teddy.lc4e.database.model.base;

import com.teddy.jfinal.interfaces.DBModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTag<M extends BaseUserTag<M>> extends DBModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public static final String id = "user_tag.id";

	public static final String ID = "ID";

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public static final String userid = "user_tag.userId";

	public static final String USERID = "USERID";

	public void setTagId(java.lang.String tagId) {
		set("tagId", tagId);
	}

	public java.lang.String getTagId() {
		return get("tagId");
	}

	public static final String tagid = "user_tag.tagId";

	public static final String TAGID = "TAGID";

	public void setPw(java.math.BigDecimal pw) {
		set("pw", pw);
	}

	public java.math.BigDecimal getPw() {
		return get("pw");
	}

	public static final String pw = "user_tag.pw";

	public static final String PW = "PW";

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public static final String createtime = "user_tag.createTime";

	public static final String CREATETIME = "CREATETIME";

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public static final String updatetime = "user_tag.updateTime";

	public static final String UPDATETIME = "UPDATETIME";

	public static final String ALL_FIELDS = "user_tag.*";
	public static final String TABLE_NAME = "user_tag";}
