package com.teddy.lc4e.database.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin_log", "id", AdminLog.class);
		arp.addMapping("sys_address", "id", SysAddress.class);
		arp.addMapping("sys_area", "id", SysArea.class);
		arp.addMapping("sys_area_status", "id", SysAreaStatus.class);
		arp.addMapping("sys_comment", "id", SysComment.class);
		arp.addMapping("sys_comment_attach", "id", SysCommentAttach.class);
		arp.addMapping("sys_common_variable", "id", SysCommonVariable.class);
		arp.addMapping("sys_dynamic_info", "id", SysDynamicInfo.class);
		arp.addMapping("sys_history_top", "id", SysHistoryTop.class);
		arp.addMapping("sys_ip_forbit", "id", SysIpForbit.class);
		arp.addMapping("sys_job", "id", SysJob.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_operate_type", "id", SysOperateType.class);
		arp.addMapping("sys_permission", "id", SysPermission.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_permission", "id", SysRolePermission.class);
		arp.addMapping("sys_tag", "id", SysTag.class);
		arp.addMapping("sys_topic", "id", SysTopic.class);
		arp.addMapping("sys_topic_attach", "id", SysTopicAttach.class);
		arp.addMapping("sys_topic_comment_status", "id", SysTopicCommentStatus.class);
		arp.addMapping("sys_topic_status", "id", SysTopicStatus.class);
		arp.addMapping("sys_url_permission", "id", SysUrlPermission.class);
		arp.addMapping("sys_url_role", "id", SysUrlRole.class);
		arp.addMapping("topic_status", "id", TopicStatus.class);
		arp.addMapping("topic_tag", "id", TopicTag.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_address", "id", UserAddress.class);
		arp.addMapping("user_area_collected", "id", UserAreaCollected.class);
		arp.addMapping("user_basicinfo", "id", UserBasicinfo.class);
		arp.addMapping("user_blocked", "id", UserBlocked.class);
		arp.addMapping("user_extend", "id", UserExtend.class);
		arp.addMapping("user_followed", "id", UserFollowed.class);
		arp.addMapping("user_message", "id", UserMessage.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("user_tag", "id", UserTag.class);
		arp.addMapping("user_topic_blocked", "id", UserTopicBlocked.class);
		arp.addMapping("user_topic_collected", "id", UserTopicCollected.class);
		arp.addMapping("user_topic_view_attitude", "id", UserTopicViewAttitude.class);
		arp.addMapping("vw_topic", "", VwTopic.class);
		arp.addMapping("vw_topic_no_pw", "", VwTopicNoPw.class);
		arp.addMapping("vw_topic_pw", "", VwTopicPw.class);
		arp.addMapping("vw_topic_status_pw", "", VwTopicStatusPw.class);
		arp.addMapping("vw_topic_tag_count_pw", "", VwTopicTagCountPw.class);
		arp.addMapping("vw_topic_user_attitude_pw", "", VwTopicUserAttitudePw.class);
		arp.addMapping("vw_user_role_permission", "", VwUserRolePermission.class);
	}
}

