package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseAdminLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "admin_log", pk = {"id"})
public class AdminLog extends BaseAdminLog<AdminLog> {
	public static final AdminLog dao = new AdminLog();
}
