package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_area", pk = {"id"})
public class SysArea extends BaseSysArea<SysArea> {
	public static final SysArea dao = new SysArea();
}
