package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_address", pk = {"id"})
public class SysAddress extends BaseSysAddress<SysAddress> {
	public static final SysAddress dao = new SysAddress();
}
