package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysAreaStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_area_status", pk = {"id"})
public class SysAreaStatus extends BaseSysAreaStatus<SysAreaStatus> {
	public static final SysAreaStatus dao = new SysAreaStatus();
}
