package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_comment", pk = {"id"})
public class SysComment extends BaseSysComment<SysComment> {
	public static final SysComment dao = new SysComment();
}
