package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysCommonVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_common_variable", pk = {"id"})
public class SysCommonVariable extends BaseSysCommonVariable<SysCommonVariable> {
	public static final SysCommonVariable dao = new SysCommonVariable();
}
