package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysDynamicInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_dynamic_info", pk = {"id"})
public class SysDynamicInfo extends BaseSysDynamicInfo<SysDynamicInfo> {
	public static final SysDynamicInfo dao = new SysDynamicInfo();
}
