package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysHistoryTop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_history_top", pk = {"id"})
public class SysHistoryTop extends BaseSysHistoryTop<SysHistoryTop> {
	public static final SysHistoryTop dao = new SysHistoryTop();
}
