package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysIpForbit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_ip_forbit", pk = {"id"})
public class SysIpForbit extends BaseSysIpForbit<SysIpForbit> {
	public static final SysIpForbit dao = new SysIpForbit();
}
