package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_job", pk = {"id"})
public class SysJob extends BaseSysJob<SysJob> {
	public static final SysJob dao = new SysJob();
}
