package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_log", pk = {"id"})
public class SysLog extends BaseSysLog<SysLog> {
	public static final SysLog dao = new SysLog();
}
