package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysOperateType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_operate_type", pk = {"id"})
public class SysOperateType extends BaseSysOperateType<SysOperateType> {
	public static final SysOperateType dao = new SysOperateType();
}
