package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_permission", pk = {"id"})
public class SysPermission extends BaseSysPermission<SysPermission> {
	public static final SysPermission dao = new SysPermission();
}
