package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_role", pk = {"id"})
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole();
}
