package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_role_permission", pk = {"id"})
public class SysRolePermission extends BaseSysRolePermission<SysRolePermission> {
	public static final SysRolePermission dao = new SysRolePermission();
}
