package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_topic", pk = {"id"})
public class SysTopic extends BaseSysTopic<SysTopic> {
	public static final SysTopic dao = new SysTopic();
}
