package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysTopicAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_topic_attach", pk = {"id"})
public class SysTopicAttach extends BaseSysTopicAttach<SysTopicAttach> {
	public static final SysTopicAttach dao = new SysTopicAttach();
}
