package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysTopicStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_topic_status", pk = {"id"})
public class SysTopicStatus extends BaseSysTopicStatus<SysTopicStatus> {
	public static final SysTopicStatus dao = new SysTopicStatus();
}
