package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysTopicCommentStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_topic_comment_status", pk = {"id"})
public class SysTopicCommentStatus extends BaseSysTopicCommentStatus<SysTopicCommentStatus> {
	public static final SysTopicCommentStatus dao = new SysTopicCommentStatus();
}
