package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_tag", pk = {"id"})
public class SysTag extends BaseSysTag<SysTag> {
	public static final SysTag dao = new SysTag();
}
