package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseSysUrlRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "sys_url_role", pk = {"id"})
public class SysUrlRole extends BaseSysUrlRole<SysUrlRole> {
	public static final SysUrlRole dao = new SysUrlRole();
}
