package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseTopicStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "topic_status", pk = {"id"})
public class TopicStatus extends BaseTopicStatus<TopicStatus> {
	public static final TopicStatus dao = new TopicStatus();
}
