package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user", pk = {"id"})
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
