package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_tag", pk = {"id"})
public class UserTag extends BaseUserTag<UserTag> {
	public static final UserTag dao = new UserTag();
}
