package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserTopicBlocked;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_topic_blocked", pk = {"id"})
public class UserTopicBlocked extends BaseUserTopicBlocked<UserTopicBlocked> {
	public static final UserTopicBlocked dao = new UserTopicBlocked();
}
