package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserTopicCollected;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_topic_collected", pk = {"id"})
public class UserTopicCollected extends BaseUserTopicCollected<UserTopicCollected> {
	public static final UserTopicCollected dao = new UserTopicCollected();
}
