package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserFollowed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_followed", pk = {"id"})
public class UserFollowed extends BaseUserFollowed<UserFollowed> {
	public static final UserFollowed dao = new UserFollowed();
}
