package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_message", pk = {"id"})
public class UserMessage extends BaseUserMessage<UserMessage> {
	public static final UserMessage dao = new UserMessage();
}
