package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserBasicinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_basicinfo", pk = {"id"})
public class UserBasicinfo extends BaseUserBasicinfo<UserBasicinfo> {
	public static final UserBasicinfo dao = new UserBasicinfo();
}
