package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserTopicViewAttitude;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_topic_view_attitude", pk = {"id"})
public class UserTopicViewAttitude extends BaseUserTopicViewAttitude<UserTopicViewAttitude> {
	public static final UserTopicViewAttitude dao = new UserTopicViewAttitude();
}
