package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_address", pk = {"id"})
public class UserAddress extends BaseUserAddress<UserAddress> {
	public static final UserAddress dao = new UserAddress();
}
