package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_extend", pk = {"id"})
public class UserExtend extends BaseUserExtend<UserExtend> {
	public static final UserExtend dao = new UserExtend();
}
