package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_role", pk = {"id"})
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
}
