package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserBlocked;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_blocked", pk = {"id"})
public class UserBlocked extends BaseUserBlocked<UserBlocked> {
	public static final UserBlocked dao = new UserBlocked();
}
