package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseUserAreaCollected;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "user_area_collected", pk = {"id"})
public class UserAreaCollected extends BaseUserAreaCollected<UserAreaCollected> {
	public static final UserAreaCollected dao = new UserAreaCollected();
}
