package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopicNoPw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic_no_pw")
public class VwTopicNoPw extends BaseVwTopicNoPw<VwTopicNoPw> {
	public static final VwTopicNoPw dao = new VwTopicNoPw();
}
