package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopicPw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic_pw")
public class VwTopicPw extends BaseVwTopicPw<VwTopicPw> {
	public static final VwTopicPw dao = new VwTopicPw();
}
