package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopicUserAttitudePw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic_user_attitude_pw")
public class VwTopicUserAttitudePw extends BaseVwTopicUserAttitudePw<VwTopicUserAttitudePw> {
	public static final VwTopicUserAttitudePw dao = new VwTopicUserAttitudePw();
}
