package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopicTagCountPw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic_tag_count_pw")
public class VwTopicTagCountPw extends BaseVwTopicTagCountPw<VwTopicTagCountPw> {
	public static final VwTopicTagCountPw dao = new VwTopicTagCountPw();
}
