package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopicStatusPw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic_status_pw")
public class VwTopicStatusPw extends BaseVwTopicStatusPw<VwTopicStatusPw> {
	public static final VwTopicStatusPw dao = new VwTopicStatusPw();
}
