package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_topic")
public class VwTopic extends BaseVwTopic<VwTopic> {
	public static final VwTopic dao = new VwTopic();
}
