package com.teddy.lc4e.database.model;

import com.teddy.jfinal.annotation.Model;
import com.teddy.lc4e.database.model.base.BaseVwUserRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Model(value = "vw_user_role_permission")
public class VwUserRolePermission extends BaseVwUserRolePermission<VwUserRolePermission> {
	public static final VwUserRolePermission dao = new VwUserRolePermission();
}
