package com.teddy.lc4e.database.generate;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.generator.TableMeta;

/**
 * Created by teddyzhu on 16/1/26.
 */
public class ModelGenerator extends com.jfinal.plugin.activerecord.generator.ModelGenerator {


    protected String importTemplate =
            "import com.teddy.jfinal.annotation.Model;%n" +
                    "import %s.%s;%n%n";

    protected String classDefineTemplate =
            "/**%n" +
                    " * Generated by JFinal.%n" +
                    " */%n" +
                    "@SuppressWarnings(\"serial\")%n" +
                    "@Model(value = \"%s\"%s)%n" +
                    "public class %s extends %s<%s> {%n";

    protected String pkTemplate = ", pk = {\"%s\"}";

    protected String daoTemplate =
            "\tpublic static final %s dao = new %s();%n";

    public ModelGenerator(String modelPackageName, String baseModelPackageName, String modelOutputDir) {
        super(modelPackageName, baseModelPackageName, modelOutputDir);
    }

    @Override
    protected void genImport(TableMeta tableMeta, StringBuilder ret) {
        ret.append(String.format(importTemplate, baseModelPackageName, tableMeta.baseModelName));
    }

    @Override
    protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
        ret.append(String.format(classDefineTemplate, tableMeta.name, StrKit.isBlank(tableMeta.primaryKey) ? "" : String.format(pkTemplate, tableMeta.primaryKey), tableMeta.modelName, tableMeta.baseModelName, tableMeta.modelName));
    }

    @Override
    protected void genDao(TableMeta tableMeta, StringBuilder ret) {
        if (generateDaoInModel)
            ret.append(String.format(daoTemplate, tableMeta.modelName, tableMeta.modelName));
        else
            ret.append(String.format("\t%n"));
    }

}
